# Generated by Django 5.0.1 on 2024-02-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_one', '0002_exampletable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampletable',
            name='f3',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
