# Generated by Django 5.0.1 on 2024-02-07 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_one', '0005_post_colloborator'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='Post_by_Authors',
        ),
    ]
