# Generated by Django 5.0.1 on 2024-02-16 06:22

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_one', '0008_example_changing_manager_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='example_changing_manager_name',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
