# Generated by Django 5.0.1 on 2024-02-16 07:11

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_one', '0009_alter_example_changing_manager_name_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, null=True)),
            ],
            managers=[
                ('custom', django.db.models.manager.Manager()),
            ],
        ),
    ]
